// Public portfolio copy. No adoption, performance or delivery metrics are inferred.
export const projects = [
  {
    id: "jurisfield", name: "JurisField", category: "Field operations",
    title: "Keep the evidence connected to the work.",
    lead: "A field-to-office workflow for geometry, photographs, forms and review — including the moments when there is no network.",
    audience: "Field teams, reviewers and workspace administrators.",
    problem: "A photograph or form is less useful when its location, assignment and review history live in separate systems. Field work also needs to continue without reliable connectivity.",
    ownership: "Product design, full-stack engineering and deployment across the web portal, Go services and native mobile clients.",
    decision: "Treat offline work as a durable record, not a temporary UI state. Versioned assignment packs, pinned draft provenance and idempotent synchronization keep collection and review connected.",
    boundary: "Server-side validation and immutable correction history are important alongside offline convenience. A successful sync is not a substitute for a reviewer’s decision.",
    stack: ["Angular", "Go", "PostGIS", "MapLibre", "SwiftUI", "Kotlin"],
    steps: [["Plan & dispatch", "Publish forms and governed layers, then assign the work."], ["Collect offline", "Capture geometry, photographs, signatures and typed responses."], ["Sync & review", "Verify receipts, review submissions and export approved records."]],
    facts: ["Offline field drafts across web, Android and iOS", "Server-side media verification and auditable receipts", "Reviewed data exports in CSV, GeoJSON and GeoPackage"],
    url: "https://jurisfield.com/", status: "Public product site", next: "Visit JurisField",
  },
  {
    id: "atlas", name: "Atlas", category: "AI media",
    title: "An inspectable path from research to video.",
    lead: "Research, narration, media planning and rendering as separate, recoverable stages rather than one opaque generation step.",
    audience: "Creators working with research-led, narrated video.",
    problem: "A generated video can look convincing while using the wrong visual, an unsupported number or a weak narrative. Fixing one stage should not require treating the whole project as a black box.",
    ownership: "Product architecture, full-stack engineering and the media pipeline across the Angular workspace, Go orchestrator and Python services.",
    decision: "Use a structured media plan between the script and render. Individual shots can be routed to footage, images or constructed graphics; numeric-grounding checks guard chart and statistic inputs.",
    boundary: "Research and automated visual checks still need human review. Publishing is an optional, explicit step after rendering, not a claim that AI output is automatically reliable.",
    stack: ["Angular", "Go", "Python", "PostgreSQL", "MinIO", "FFmpeg"],
    steps: [["Research & write", "Build the narration and segment it into a media plan."], ["Plan & produce", "Source or construct visuals and generate clip-level narration."], ["Review & render", "Inspect the storyboard, assemble with FFmpeg and optionally publish."]],
    facts: ["Versioned declarative visual-rendering contracts", "Per-project script, storyboard and media storage", "Separate narration, rendering and publishing stages"],
    url: "https://atlas.santhoshbalaji.cloud/", status: "Public product site", next: "Visit Atlas",
  },
  {
    id: "nammatn", name: "NammaTN", category: "Civic technology",
    title: "Make local issues easier to follow.",
    lead: "An independent civic product connecting local reporting, community context and transparent follow-through in Tamil and English.",
    audience: "Residents following issues in their local communities.",
    problem: "Reporting an issue is only the beginning. People also need location context, ways to verify what is happening and a public trail they can return to.",
    ownership: "Founder, product direction and full-stack engineering across the civic interface and its spatial services.",
    decision: "Keep the issue connected to geography and jurisdiction, with bilingual participation and community verification as parts of the workflow.",
    boundary: "NammaTN is independent civic technology, not an official government service. A report or community verification does not establish an official resolution.",
    stack: ["Angular", "Go", "PostgreSQL", "PostGIS", "D3 Geo", "Docker"],
    steps: [["Report locally", "Describe an issue with its place and supporting context."], ["Verify together", "Add community evidence and jurisdiction context."], ["Follow the record", "Return to the public trail and track reported follow-through."]],
    facts: ["Tamil and English interface", "Location-aware reporting and map views", "Community verification and transparent tracking"],
    image: "assets/projects/nammatn-interface.webp",
    imageAlt: "NammaTN mobile interface preview showing sign-in, community feed, reporting, verification and a map",
    imageCaption: "Product interface preview from the NammaTN project. The examples shown are demonstration content, not usage or adoption statistics.",
    url: "https://nammatn.in/", status: "Public product site", next: "Visit NammaTN",
  },
  {
    id: "mapsmith", name: "MapSmith", category: "GIS infrastructure",
    title: "A spatial platform you can build on.",
    lead: "Self-hosted GIS that connects spatial data, map authoring and analysis with programmable APIs and a CLI.",
    audience: "Developers and teams publishing and operating spatial services.",
    problem: "A map interface alone is not a GIS platform. Teams also need hosted data, permissions, repeatable analysis and a way to automate the same workflows outside the browser.",
    ownership: "Product architecture, full-stack engineering and platform operations.",
    decision: "Build on PostGIS and MapLibre, with a Go service layer and a shared API surface for the web workspace, SDK and CLI. Analysis jobs produce hosted layers that can be used in maps.",
    boundary: "The platform is an evolving implementation, not a claim of feature parity with mature enterprise GIS suites. Self-hosting gives deployment control but also carries an operational responsibility.",
    stack: ["Angular", "Go", "PostGIS", "MapLibre", "Keycloak", "Docker"],
    steps: [["Data & services", "Publish collections and serve spatial features and vector tiles."], ["Maps & analysis", "Author maps and run server-side spatial operations."], ["SDK & automation", "Use APIs and the CLI for publishing, queries and platform workflows."]],
    facts: ["PostGIS-backed vector tiles and hosted collections", "Server-side analysis producing new spatial layers", "SDK and CLI access to the same platform services"],
    status: "Self-hosted platform · architecture notes",
  },
];
